FROM node:20-alpine

RUN apk add --no-cache curl

WORKDIR /repo

# pnpm via corepack
RUN corepack enable
RUN corepack prepare pnpm@10.29.3 --activate

# Copiamos solo manifests para cache
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/api/package.json apps/api/package.json
COPY packages/database-core/package.json packages/database-core/package.json

ENV CI=true
RUN mkdir -p /pnpm-store \
  && pnpm config set store-dir /pnpm-store \
  && pnpm config set package-import-method copy

EXPOSE 4000
CMD ["sh", "-lc", "pnpm config set store-dir /pnpm-store && pnpm config set package-import-method copy && pnpm install --frozen-lockfile && pnpm --filter @tabblelab/database-core build && pnpm --filter api dev"]